### ISSUE TITLE
脚本运行时不稳定问题

### ISSUE THREAD

**Issue by jiankeyan13** [CXRunfree/Autovisor#14]
问题描述：脚本在运行时存在不工作问题。
具体情况：![屏幕截图 2024-04-04 231017](https://github.com/CXRunfree/Autovisor/assets/118413459/1d8102d3-909f-488b-b761-22c92f6663dd)
如图，5.2在智慧树界面已经结束，但脚本仍停留在5.2初始阶段。当网页中5.2以正常速度结束后，无法自动续播。

**Comment by CXRunfree** [comment]
确实存在莫名卡住的问题，我猜测是弹题导致的，在3.11版本可能得到解决，但具体还得通过后续反馈来检验
