### ISSUE TITLE
[bug]视频中的图形验证无法验证&&长时间刷视频会网页会卡死，需要重新运行脚本

### ISSUE THREAD

**Issue by Arsiendle** [CXRunfree/Autovisor#21]
p1
![image](https://github.com/CXRunfree/Autovisor/assets/128237447/53b6f22c-43a8-4312-9146-eab6206f60cf)
p2
虽然显示的是播放不是暂停，但实际上这里已经卡死了，不能动了
![image](https://github.com/CXRunfree/Autovisor/assets/128237447/2525bdb8-a233-48a1-bc96-d59b4581650c)

**Comment by CXRunfree** [comment]
p1的问题在文档中已经指出, 无法自动验证; p2出现的原因有很多, 暂时没找到好的解决办法
