### ISSUE TITLE
无法刷见面课

### ISSUE THREAD

**Issue by PiaoMaker** [CXRunfree/Autovisor#23]
RT,见面课的url：https://lc.zhihuishu.com/live/vod_room.html?t=1719158399000&liveId=10767484&courseId=1000006172&recruitId=239241，会报错为无效网址

![af79e166b7ed8e6af8d1415fe0b779e5.png](https://i.mjj.rip/2024/05/22/af79e166b7ed8e6af8d1415fe0b779e5.png)

**Comment by CXRunfree** [comment]
这个不是bug，目前只支持共享课，后续会考虑适配见面课
