### ISSUE TITLE
Linux System Compatibility

### ISSUE THREAD

**Issue by HXavier21** [CXRunfree/Autovisor#26]
## Env
Arch Linux

## Issue
Release打包的exe文件使用Wine运行时无法正常启动Edge（path: /opt/microsoft/msedge/msedge）
Clone项目至本地后直接执行Autovisor.py则可以成功启动（配置path设置上述path或置空均可）
> 猜测windows编译exe时应用唤起相关动态链接库无法在linux环境下正确运行

## Propose
Release中添加linux编译生成的可执行文件

**Comment by CXRunfree** [comment]
感谢反馈，不过鉴于Linux有现成的py环境，直接运行源代码更方便，所以就没打算提供编译文件；相比之下Windows没有现成环境，故提供编译好的exe是更有必要的。
