### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by Disaster-Terminator** [CXRunfree/Autovisor#32]
登录后跳转至听课网页时闪退，
TimeoutError应当是playwright里的, 而不是buildins里的
![cb3df463b2dd12571a586ded9fd5b46e](https://github.com/user-attachments/assets/9ae793b7-2ef9-4f89-acb9-53643c002e47)

**Comment by CXRunfree** [comment]
确实存在这个问题, utils.py里捕获的TimeoutError实际来自于playwright.async_api,  但错误使用了内置的TImeoutError类, 从而导致闪退. 目前已经撤下3.14.1版本, 在3.14.2版本进行了修复.
