### ISSUE TITLE
由于自动进入inprivate模式打不开视频播放页 

### ISSUE THREAD

**Issue by Towel-Fish** [CXRunfree/Autovisor#35]
您好， 我的系统为win11，在我的电脑中 `p.chromium.launch(channel=“msedge”, headless=False)` 默认打开的是 edge浏览器 的inprivate模式。
经过我的手测，似乎在这个模式下无法打开视频播放界面。
我的解决方法是不使用playwright提供的打开新浏览器的方式，使用edge浏览器的remote debug模式可以临时解决这个问题
根据[playwright连接已有浏览器操作](https://blog.csdn.net/wx17343624830/article/details/130485762)

大概是这样修改的，分别位于32和45行，我直接填了绝对路径

```        
            #browser = await p.chromium.launch(channel=driver, headless=False)
            browser = await p.chromium.launch_persistent_context
        (
            user_data_dir=r"D:\user_data",
            executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
            headless=False,
            bypass_csp=True,
            slow_mo=10,
            args=['--disable-blink-features=AutomationControlled','--remote-debugging-port=9222']
        )
```

```   
    #context = await browser.new_context()
    page = await browser.new_page()
```

不知道为什么直接使用您提供的代码就只能打开inprivate模式，似乎和用户数据有关。以及不知道为什么在inprivate模式下不能播放视频。

**Comment by Towel-Fish** [comment]
而且每次重新运行我必须删除user_data文件夹才能正常使用

**Comment by Towel-Fish** [comment]
https://cloud.tencent.com/developer/article/2315189

**Comment by CXRunfree** [comment]
隐私模式不会影响视频播放的，至于remote debug(cdp)会干扰现有的浏览器实例所以选择新开一个；inprivate确实不太方便，后续会考虑改成正常模式

**Comment by Towel-Fish** [comment]
@CXRunfree 感谢回复！
电脑端的inprivate打开的视频播放页就是一片空白，body的大小是1280x0，手机的inprivate就可以。应该是我这边edge的问题。

**Comment by Towel-Fish** [comment]
本次更新之后问题解决了
