### ISSUE TITLE
无法打开edge

### ISSUE THREAD

**Issue by HorizontalWorld** [CXRunfree/Autovisor#4]
json文件改了如下，打不开浏览器。大佬求解 <3
{
    "User": "1 ",
    "Password": "1 ",
    "Driver": "Edge "
    "Url": "https://studyvideoh5.zhihuishu.com/stuStudy?recruitAndCourseId=XXX ",
}

**Comment by HorizontalWorld** [comment]
我现在改了，只把网址进行了替换
{
    "User": "1 ",
    "Password": "1 ",
    "Driver": " Edge ",
    "Url": ["https://studyvideoh5.zhihuishu.com/stuStudy?recruitAndCourseId=XXX ",
            "以上是一个示范,可以继续增加网址,以英文逗号隔开 " 
            ]
    
}
那段中文还留着，"前面也空格了，依然没什么反应，程序好像突然打开然后就关了😭

**Comment by CXRunfree** [comment]
请把目录下的log.txt里的报错信息贴出来看一下

**Comment by HorizontalWorld** [comment]
我没有找到log.txt，运行界面一开就自己关掉了

**Comment by CXRunfree** [comment]
你可以确定下的是发行版程序而不是源代码? 除非出现文件缺失, 否则是不会闪退的, 建议下载最新发行版试试吧

**Comment by CXRunfree** [comment]
log.txt只能捕获运行时的错误, 你这情况显然是程序没跑起来

**Comment by HorizontalWorld** [comment]
是压缩包吗，我现下载的是那个压缩包然后解压的。点开程序会打开网页，但会停在登录界面，要手点登录再滑块，然后就怎么点开程序都没法运行了

**Comment by HorizontalWorld** [comment]
[Autovisor-for-Windows.zip](https://github.com/CXRunfree/Autovisor/releases/download/2024%2F3%2F2/Autovisor-for-Windows.zip)
这个点进去是not found

**Comment by CXRunfree** [comment]
从你的描述我无法确定是什么原因, 建议寻找身边更专业的人进行调试; 如果进度一直卡在 "载入数据...", 那么多等一会就能启动浏览器。

**Comment by 2613df** [comment]
遇到类似问题，不论chrome或edge
![Quicker_20240306_152938](https://github.com/CXRunfree/Autovisor/assets/7090590/a21961f1-9ff5-4958-a91e-eec3bfc67f4b)
这个chrome browser是启动程序后自动下载的版本，并非系统自带
