### ISSUE TITLE
登录人机验证问题和视频播放问题

### ISSUE THREAD

**Issue by Nathan14629** [CXRunfree/Autovisor#44]
登录的人机验证并没有通过就强行跳转至课程界面，导致网站要你跳回去验证，程序又跳回来刷课导致卡死，这里建议博主直接回滚项目，取消登录时的自动验证功能，效率最高。500ms的等待时间太短了，滑动验证根本加载不完，直接加长等待时间可能行，我没看跳验证的代码，如果不行直接回滚最好也最快。我看路子野的有登录直接刷cookie的，博主得闲可以试试。
然后是视频播放问题，目前最大的问题是，当前视频进度刷满后不会自动跳转到下一个视频，盲猜是检测到暂停后自动播放的问题，可能是该功能优先度比自动播放下一视频高？然后是进度问题，1.8x下进度不同步，而且正好视频要刷1.2遍进度才能拉满，盲猜是智慧树做了时钟计时，这个好解决，config文件里速率改成1.5就行。
再多句嘴，博主的第三方库最好打在包里，在下一个稳定的大发行版上能直接本地部署，一是防止供应链投毒，二是防止三方更新后因为点奇奇怪怪的原因程序跑不了，因为我觉得博主这作品能成为刷课软件的标杆，star奉上
以下致用户，目前3.14.4发行版本滑块验证的解决方案：卡死之后尽快手动停止网页跳转，然后直接回退到登录界面手动登录验证，完成后直接cv网课链接跳转到播放，可以暂时解决人机验证失败导致的卡死。

**Comment by Towel-Fish** [comment]
> 登录的人机验证并没有通过就强行跳转至课程界面，导致网站要你跳回去验证，程序又跳回来刷课导致卡死，这里建议博主直接回滚项目，取消登录时的自动验证功能，效率最高。500ms的等待时间太短了，滑动验证根本加载不完，直接加长等待时间可能行，我没看跳验证的代码，如果不行直接回滚最好也最快。我看路子野的有登录直接刷cookie的，博主得闲可以试试。
> 然后是视频播放问题，目前最大的问题是，当前视频进度刷满后不会自动跳转到下一个视频，盲猜是检测到暂停后自动播放的问题，可能是该功能优先度比自动播放下一视频高？然后是进度问题，1.8x下进度不同步，而且正好视频要刷1.2遍进度才能拉满，盲猜是智慧树做了时钟计时，这个好解决，config文件里速率改成1.5就行。
> 再多句嘴，博主的第三方库最好打在包里，在下一个稳定的大发行版上能直接本地部署，一是防止供应链投毒，二是防止三方更新后因为点奇奇怪怪的原因程序跑不了，因为我觉得博主这作品能成为刷课软件的标杆，star奉上
> 以下致用户，目前3.14.4发行版本滑块验证的解决方案：卡死之后尽快手动停止网页跳转，然后直接回退到登录界面手动登录验证，完成后直接cv网课链接跳转到播放，可以暂时解决人机验证失败导致的卡死。

等待滑块验证用的是--loading属性验证，超时时间默认30s，按理说不会是没加载完的问题

**Comment by CXRunfree** [comment]
感谢您的建议， 未登录就强行跳转播放页确实是一个恶性bug，原因是判断登录完成的函数放在了图形验证的函数里，如果autoCaptcha为False这部分逻辑就不会启用。目前只在3.14.4版本存在，更新至3.15版本后解决了该问题。
