### ISSUE TITLE
登录结束后网页持续刷新，无法打开播放页

### ISSUE THREAD

**Issue by Charlesssong** [CXRunfree/Autovisor#45]
![0e17bc3275c16a027b38c02974d4221](https://github.com/user-attachments/assets/8f10f38e-7360-4125-b75a-2d014d81a37d)
![45e29d14c167c68c4e94a86dae5d278](https://github.com/user-attachments/assets/d5bac187-94c4-41e0-aa42-44eacff48370)

**Comment by xcwl520** [comment]
问题是验证码还没验证通过软件就跳转到课程列表了

**Comment by ecnudon** [comment]
刚刚我也出现了这种情况, 因为这是InPrivate页面, 所以没法自动登录; 你可以快速点击右边的那个"问答", 在一个新的页面完成登录, 这里就刷新出来结果了~

**Comment by nemeshisu003** [comment]
我也是这个问题 只有通过在另一个页面登入解决

**Comment by CXRunfree** [comment]
这个问题是个bug, 在3.15版本应该得到解决了
