### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by cqep** [CXRunfree/Autovisor#5]
edge浏览器打开之后出现如下错误

Error:<class 'selenium.common.exceptions.JavascriptException'>
错误日志已保存至:log.txt
系统异常,要不重启一下

**Comment by CXRunfree** [comment]
是每次必现还是偶然出现？请附上log.txt的内容

**Comment by cqep** [comment]
大佬 为什么你这个  release 一打开就显示404啊

**Comment by cqep** [comment]
大佬 你这个releases 为什么一打开就显示404啊

**Comment by CXRunfree** [comment]
你指的是Github下载界面还是智慧树的界面? 我这边测试没问题哒

**Comment by CXRunfree** [comment]
我在README里加上了国内下载源,这下应该没问题吧

**Comment by cqep** [comment]
> 你指的是Github下载界面还是智慧树的界面？我这边测试没问题哒

GitHub里面的 releases

**Comment by cqep** [comment]
> 你指的是Github下载界面还是智慧树的界面？我这边测试没问题哒

使用了油猴脚本之后 可以下载了 我再试一下

**Comment by cqep** [comment]
> 你指的是Github下载界面还是智慧树的界面？我这边测试没问题哒

使用油猴脚本之后 可以下载了 我再试一下刷课程序

**Comment by cqep** [comment]
错误是这样的 

Traceback (most recent call last):
  File "Autovisor.py", line 167, in <module>
  File "Autovisor.py", line 66, in get_lesson_name
  File "selenium\webdriver\support\wait.py", line 101, in until
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF7A585B852+63538]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7A57DF6D2+238290]
	(No symbol) [0x00007FF7A5613407]
	(No symbol) [0x00007FF7A56597ED]
	(No symbol) [0x00007FF7A56598B0]
	(No symbol) [0x00007FF7A5694387]
	(No symbol) [0x00007FF7A5678E5F]
	(No symbol) [0x00007FF7A564F037]
	(No symbol) [0x00007FF7A5691F49]
	(No symbol) [0x00007FF7A5678A83]
	(No symbol) [0x00007FF7A564E55E]
	(No symbol) [0x00007FF7A564D71C]
	(No symbol) [0x00007FF7A564E111]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7A5A31D3C+1102764]
	(No symbol) [0x00007FF7A56C25F6]
	(No symbol) [0x00007FF7A5753DAC]
	(No symbol) [0x00007FF7A574BDA8]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF7A5A30C85+1098485]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7A57E9E91+281233]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7A57E4614+258580]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7A57E474F+258895]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF7A57D8F21+211745]
	BaseThreadInitThunk [0x00007FF8CC96257D+29]
	RtlUserThreadStart [0x00007FF8CD4AAA78+40]

**Comment by CXRunfree** [comment]
脚本多少会有点瑕疵, 多试几次, 应该是能用的; 另外最好改善一下你的网络环境

**Comment by cqep** [comment]
还是有问题 进入课程界面之后 课程列表还没有加载出来 就直接退出来了

Traceback (most recent call last):
  File "Autovisor.py", line 167, in <module>
  File "Autovisor.py", line 66, in get_lesson_name
  File "selenium\webdriver\support\wait.py", line 101, in until
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF795F8B852+63538]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF795F0F6D2+238290]
	(No symbol) [0x00007FF795D43407]
	(No symbol) [0x00007FF795D897ED]
	(No symbol) [0x00007FF795D898B0]
	(No symbol) [0x00007FF795DC4387]
	(No symbol) [0x00007FF795DA8E5F]
	(No symbol) [0x00007FF795D7F037]
	(No symbol) [0x00007FF795DC1F49]
	(No symbol) [0x00007FF795DA8A83]
	(No symbol) [0x00007FF795D7E55E]
	(No symbol) [0x00007FF795D7D71C]
	(No symbol) [0x00007FF795D7E111]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF796161D3C+1102764]
	(No symbol) [0x00007FF795DF25F6]
	(No symbol) [0x00007FF795E83DAC]
	(No symbol) [0x00007FF795E7BDA8]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF796160C85+1098485]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF795F19E91+281233]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF795F14614+258580]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF795F1474F+258895]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF795F08F21+211745]
	BaseThreadInitThunk [0x00007FF94777257D+29]
	RtlUserThreadStart [0x00007FF94874AA78+40]

**Comment by CXRunfree** [comment]
从完成登录到进入网课的过程是不需要你点击操作的，我猜测你点了“我的学堂”

**Comment by CXRunfree** [comment]
目前程序使用的框架确实不稳定，日后也会考虑重构的

**Comment by cqep** [comment]
> 从完成登录到进入网课的过程是不需要你点击操作的，我猜测你点了“我的学堂”

没有哎 大佬

**Comment by CXRunfree** [comment]
我已经给程序换了更稳定的框架, 先试试新版的效果吧

**Comment by cqep** [comment]
打开之后就加载了
![VeryCapture_20240306184314](https://github.com/CXRunfree/Autovisor/assets/153111824/e835620b-0194-48f1-9fcd-d0019527856f)

**Comment by CXRunfree** [comment]
我算是明白了，你没填网址啊，建议仔细看一看说明文档介绍account的说明吧

**Comment by CXRunfree** [comment]
你得把想刷的那节课的网址复制到account文件里去，文件初始给出的只是一个模板呀

**Comment by cqep** [comment]
> 你得把想刷的那节课的网址复制到account文件里去，文件初始给出的只是一个模板呀

不好意思 大佬 真的没有看见

**Comment by cqep** [comment]
但是这样好麻烦啊 大佬 后续可不可以简化一下

**Comment by CXRunfree** [comment]
解决不显示课程信息的问题还有点难度, 只能是慢慢来吧。不过你填一次就可以一直用了

**Comment by cqep** [comment]
> 解决不显示课程信息的问题还有点难度, 只能是慢慢来吧。不过你填一次就可以一直用了

大佬 加油加油 希望后续可以修复
