### ISSUE TITLE
无法加载播放页

### ISSUE THREAD

**Issue by Beetlesliu** [CXRunfree/Autovisor#51]
![{EA5175A9-92AE-4453-AD8E-1FA0DB841877}](https://github.com/user-attachments/assets/82918836-1f5d-4d0b-8e33-83380889868a)

**Comment by Beetlesliu** [comment]
通过修改配置文件自动通过验证码改为True已解决

**Comment by CXRunfree** [comment]
这个bug会在未完成登录就强制进入播放页, 目前只在3.14版本存在, 3.15版本已经修复.
