### ISSUE TITLE
播放页黑屏

### ISSUE THREAD

**Issue by 1355930415** [CXRunfree/Autovisor#57]
在打开课程界面后黑屏

不使用程序正常打开课程界面

发现正常打开的地址栏里没有%20%20%20...

手动把程序打开的课程页面里的地址删去%20之后的内容，回车。程序正常运行。
本身程序没有崩溃，只是卡住。为获取日志，手动在21：59整关闭浏览器窗口。

**Comment by 1355930415** [comment]
[Log2.txt](https://github.com/user-attachments/files/17619427/Log2.txt)
[configs.txt](https://github.com/user-attachments/files/17619460/configs.txt)
![Screenshot 2024-11-04 215803](https://github.com/user-attachments/assets/fe029102-006c-4f07-aa01-841632ab1366)
![Screenshot 2024-11-04 215832](https://github.com/user-attachments/assets/0e0cc648-cf73-4897-9d31-494c6c0d9e1f)

**Comment by 1355930415** [comment]
![20241104222812](https://github.com/user-attachments/assets/716a0bd5-7152-47dc-9999-fed02ea7957e)

**Comment by 1355930415** [comment]
完整的异常链接：
https://studyvideoh5.zhihuishu.com/stuStudy?recruitAndCourseId=485d585b475c4859454a58595144594050%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Bguofang

**Comment by CXRunfree** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/79dfd25a-d118-400f-a4d5-34366e6e9979">
如图, 你的配置文件内容格式有问题, 你手动删掉这些特殊符号并改成正确的网址再试试。另外配置文件应该是configs.ini, 你的为什么是configs.txt ?

**Comment by 1355930415** [comment]
谢大佬，明白了。
configs.txt是因为github传不上以ini结尾的附件（bushi)
