### ISSUE TITLE
没有进行执行并超时，没有一次成功

### ISSUE THREAD

**Issue by lonely622814** [CXRunfree/Autovisor#6]
进入后没有进行执行而是卡顿了，但是我的网络没有问题
[log.txt](https://github.com/CXRunfree/Autovisor/files/14494094/log.txt)

**Comment by lonely622814** [comment]
并没有正常加入课表

**Comment by lonely622814** [comment]
<img width="1280" alt="image" src="https://github.com/CXRunfree/Autovisor/assets/152073038/a6c9d77c-a6be-4afd-ad70-24a9cb42c642">

**Comment by lonely622814** [comment]
<img width="1022" alt="image" src="https://github.com/CXRunfree/Autovisor/assets/152073038/ee935696-645c-44b1-ac6d-24c8d3b9b4dc">

**Comment by RichY0608** [comment]
> <img alt="image" width="1022" src="https://private-user-images.githubusercontent.com/152073038/310091378-ee935696-645c-44b1-ac6d-24c8d3b9b4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzgwMzksIm5iZiI6MTcwOTYzNzczOSwicGF0aCI6Ii8xNTIwNzMwMzgvMzEwMDkxMzc4LWVlOTM1Njk2LTY0NWMtNDRiMS1hYzZkLTI0YzhkM2I5YjRkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzhkMDkxMTE1NTk0ZWY1ZWM1Zjk1YTk3NTNmZGE1OWZkM2NiOWFmNGNjM2I1YWE5ZjA1NzIzOGFkODgxYzZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c5GW8syxo_ha-lwbXxV51Ts2igy0VnoJzoUm5GI-6sM">

我都没有这个页面

**Comment by RichY0608** [comment]
加载到 我的学堂 就异常了

**Comment by CXRunfree** [comment]
登录完成会显示主页，然后直接进入网课界面，这中间并不会经过“我的学堂”；我猜测是你主动点击导致跳转失败了

**Comment by RichY0608** [comment]
> 登录完成会显示主页，然后直接进入网课界面，这中间并不会经过“我的学堂”；我猜测是你主动点击导致跳转失败了

滑块是我点的

**Comment by CXRunfree** [comment]
从完成登录后到进入网课的过程不需要点击，是自动的

**Comment by RichY0608** [comment]
> 从完成登录后到进入网课的过程不需要点击，是自动的

好的 我等会试试

**Comment by CXRunfree** [comment]
智慧树检查机制较为严格，会屏蔽“我的学堂”里的课程信息；所以让用户预填网课网址就能够绕过限制，直接进网课

**Comment by RichY0608** [comment]
> 智慧树检查机制较为严格，会屏蔽“我的学堂”里的课程信息；所以让用户预填网课网址就能够绕过限制，直接进网课

预
填网址 填写课程里的网址是吧

**Comment by lonely622814** [comment]
如果我不点击，他就会直接不执行，300秒后退出程序了

**Comment by CXRunfree** [comment]
我已经给程序换了更稳定的框架, 先试试新版的效果吧

**Comment by CXRunfree** [comment]
> 如果我不点击，他就会直接不执行，300秒后退出程序了

你是不是也没有在account文件里填入网课的地址(具体到课程)? 有个与你一样的问题就是这个原因

**Comment by RichY0608** [comment]
> > 如果我不点击，他就会直接不执行，300秒后退出程序了
> 
> 你是不是也没有在account文件里填入网课的地址(具体到课程)? 有个与你一样的问题就是这个原因

有答题测验的功能么

**Comment by CXRunfree** [comment]
> > > 如果我不点击，他就会直接不执行，300秒后退出程序了
> > 
> > 
> > 你是不是也没有在account文件里填入网课的地址(具体到课程)? 有个与你一样的问题就是这个原因
> 
> 有答题测验的功能么

所有功能都写在说明文档里了。刷题脚本油猴有现成的，所以我不打算再开发
