### ISSUE TITLE
edge/chrome版本错误问题

### ISSUE THREAD

**Issue by 2613df** [CXRunfree/Autovisor#7]
你好作者大大，
经自我排查，因先前测试使用过类似库，也安装了chrome/edge driver，因此在默认python目录下会有旧版本的chrome/edge driver，但是浏览器自动更新导致chrome/edge driver版本不匹配。导致黑屏闪退，其他issue提到的黑屏闪退问题可能来源于这个问题，而且也没有log文件。即使自动下载新chrome，也会因为环境中存在旧driver而闪退
解决方案：下载新的driver覆盖即可，要求与chrome/egde浏览器版本匹配。
附上edge driver: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/?form=MA13LH#downloads
或许可以检测浏览器版本下载指定版本的driver到本地，并指定driver文件的位置来一劳永逸解决这个问题
截图来自手速
![Quicker_20240306_154445](https://github.com/CXRunfree/Autovisor/assets/7090590/edac8c78-494e-4a6c-b810-36b783697388)

**Comment by CXRunfree** [comment]
你说的很有道理, 不过我决定改用微软的playwright库来改善稳定性, 这个库似乎能自动更新driver来匹配浏览器的版本; 如果后续还出现此类问题会参考你的意见来修改的 !
